package com.unsis.view.panel;

import java.awt.CardLayout;

/**
 *
 * @author labtecweb09
 */
public class Accounting extends javax.swing.JPanel {

    /**
     * Creates new form Venta
     */
    public Accounting() {
        initComponents();

        configureCardPanel();
    }

    /**
     * Add JPanels to panel with card layout for change
     */
    private void configureCardPanel() {
        panelDefault.add("Corte de caja", new ClosingSales());
        panelDefault.add("Gastos", new RegisterExpenses());
    }

    /**
     * Change the panel view
     *
     * @param name key for JPanel to show
     */
    public void setView(String name) {
        CardLayout c1 = (CardLayout) (panelDefault.getLayout());
        c1.show(panelDefault, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroupPanel = new javax.swing.ButtonGroup();
        panelDefault = new javax.swing.JPanel();
        buttonGast = new javax.swing.JToggleButton();
        buttonCourt = new javax.swing.JToggleButton();

        jRadioButton1.setText("jRadioButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDefault.setLayout(new java.awt.CardLayout());
        add(panelDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 1370, 920));

        buttonGast.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroupPanel.add(buttonGast);
        buttonGast.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGast.setForeground(new java.awt.Color(255, 255, 255));
        buttonGast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courtIcon.png"))); // NOI18N
        buttonGast.setText("Gastos");
        buttonGast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonGast.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(buttonGast, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 130, 90));

        buttonCourt.setBackground(new java.awt.Color(255, 213, 131));
        buttonGroupPanel.add(buttonCourt);
        buttonCourt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCourt.setForeground(new java.awt.Color(255, 255, 255));
        buttonCourt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courtIcon.png"))); // NOI18N
        buttonCourt.setSelected(true);
        buttonCourt.setText("Corte de Caja");
        buttonCourt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCourt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCourt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonCourtStateChanged(evt);
            }
        });
        add(buttonCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCourtStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonCourtStateChanged
        String window = buttonCourt.isSelected() ? "Corte de caja" : "Gastos";
        setView(window);

    }//GEN-LAST:event_buttonCourtStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonCourt;
    private javax.swing.JToggleButton buttonGast;
    private javax.swing.ButtonGroup buttonGroupPanel;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel panelDefault;
    // End of variables declaration//GEN-END:variables
}
