/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unsis.view.panel;

import javax.swing.JLabel;

/**
 *
 * @author Cristoforo
 */
public class ChildWrapperPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildWrapperPanel
     */
    public ChildWrapperPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrder = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        txtOrder.setEditable(false);
        txtOrder.setBackground(new java.awt.Color(255, 255, 255));
        txtOrder.setColumns(20);
        txtOrder.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtOrder.setForeground(new java.awt.Color(51, 51, 51));
        txtOrder.setRows(5);
        txtOrder.setText("1.- 2 Tortas de Tasajo\n2.- 1 Agua 600ml\n3.- 2 Tlayudas\n4.- 5 Tacos de chorizo\n");
        txtOrder.setAutoscrolls(false);
        txtOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtOrder.setMinimumSize(new java.awt.Dimension(199, 25));
        jScrollPane1.setViewportView(txtOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOrder;
    // End of variables declaration//GEN-END:variables
}
