/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author 52951
 */
public class DetallesVenta extends javax.swing.JPanel {

    /**
     * Creates new form DetallesVenta
     */
    public DetallesVenta() {
        initComponents();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        vendedorLabel = new javax.swing.JLabel();
        compradorLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        nameVendedorLabel = new javax.swing.JLabel();
        nameCompradorLabel = new javax.swing.JLabel();
        ingresoMontoLabel = new javax.swing.JLabel();
        ingresarFechaLabel = new javax.swing.JLabel();
        confirmarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        cerrarBoton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(15, 36, 109));
        jLabel1.setFont(new java.awt.Font("Jaldi", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 36, 109));
        jLabel1.setText("Detalles de la venta");

        vendedorLabel.setBackground(new java.awt.Color(118, 125, 142));
        vendedorLabel.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        vendedorLabel.setForeground(new java.awt.Color(118, 125, 142));
        vendedorLabel.setText("Vendedor");

        compradorLabel.setBackground(new java.awt.Color(118, 125, 142));
        compradorLabel.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        compradorLabel.setForeground(new java.awt.Color(118, 125, 142));
        compradorLabel.setText("Comprador");

        montoLabel.setBackground(new java.awt.Color(118, 125, 142));
        montoLabel.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(118, 125, 142));
        montoLabel.setText("Monto de la venta");

        fechaLabel.setBackground(new java.awt.Color(118, 125, 142));
        fechaLabel.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(118, 125, 142));
        fechaLabel.setText("Fecha y hora de venta");

        nameVendedorLabel.setBackground(new java.awt.Color(118, 125, 142));
        nameVendedorLabel.setFont(new java.awt.Font("Jaldi", 0, 12)); // NOI18N
        nameVendedorLabel.setForeground(new java.awt.Color(118, 125, 142));
        nameVendedorLabel.setText("Hugo López");
        nameVendedorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        nameCompradorLabel.setBackground(new java.awt.Color(118, 125, 142));
        nameCompradorLabel.setFont(new java.awt.Font("Jaldi", 0, 12)); // NOI18N
        nameCompradorLabel.setForeground(new java.awt.Color(118, 125, 142));
        nameCompradorLabel.setText("Pedro (taxista)");
        nameCompradorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ingresoMontoLabel.setForeground(new java.awt.Color(118, 125, 142));
        ingresoMontoLabel.setText("$");
        ingresoMontoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ingresarFechaLabel.setBackground(new java.awt.Color(118, 125, 142));
        ingresarFechaLabel.setFont(new java.awt.Font("Jaldi", 0, 12)); // NOI18N
        ingresarFechaLabel.setForeground(new java.awt.Color(118, 125, 142));
        ingresarFechaLabel.setText("3 de Octubre 2023 10:15:45");

        confirmarBoton.setBackground(new java.awt.Color(25, 130, 206));
        confirmarBoton.setFont(new java.awt.Font("Jaldi", 0, 12)); // NOI18N
        confirmarBoton.setForeground(new java.awt.Color(255, 255, 255));
        confirmarBoton.setText("Confirmar compra");
        confirmarBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(montoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(vendedorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(compradorLabel)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nameVendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameCompradorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ingresoMontoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ingresarFechaLabel)
                                .addGap(14, 14, 14)))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmarBoton)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendedorLabel)
                    .addComponent(compradorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameVendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameCompradorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoLabel)
                    .addComponent(fechaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoMontoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarFechaLabel))
                .addGap(46, 46, 46)
                .addComponent(confirmarBoton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 400, 380));

        Table.setFont(new java.awt.Font("Jaldi", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Text", "Text", "1", "Text", "Text"},
                {"Text", "Text", "2", "Text", "Text"},
                {"Text", "Text", "4", "Text", "Text"},
                {"Text", "Text", "5", "Text", "Text"},
                {"Text", "Text", "7", "Text", "Text"},
                {"Text", "Text", "7", "Text", "Text"},
                {"Text", "Text", "1", "Text", "Text"},
                {"Text", "Text", "5", "Text", "Text"},
                {"Text", "Text", "5", "Text", "Text"},
                {"Text", "Text", "8", "Text", "Text"},
                {"Text", "Text", "5", "Text", "Text"},
                {"Text", "Text", "5", "Text", "Text"},
                {"Text", "Text", "7", "Text", "Text"},
                {"Text", "Text", "2", "Text", "Text"},
                {"Text", "Text", "2", "Text", "Text"}
            },
            new String [] {
                "Productos", "Descripción", "Cantidad", "Precio por pieza", "Total"
            }
        ));
        Table.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(Table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 380));

        cerrarBoton.setBackground(new java.awt.Color(242, 242, 242));
        cerrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        cerrarBoton.setBorder(null);
        cerrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBotonActionPerformed(evt);
            }
        });
        add(cerrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents


    private void cerrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton cerrarBoton;
    private javax.swing.JLabel compradorLabel;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel ingresarFechaLabel;
    private javax.swing.JLabel ingresoMontoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JLabel nameCompradorLabel;
    private javax.swing.JLabel nameVendedorLabel;
    private javax.swing.JLabel vendedorLabel;
    // End of variables declaration//GEN-END:variables
}
