package com.unsis.view.panel;

import com.unsis.clases.Tools;
import com.unsis.controller.JpaController;
import com.unsis.models.entity.Company;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Elio
 */
public class FirstEjecutation extends javax.swing.JFrame {

    private String logo = "";
    private String name = "";
    private String description = "";

    /**
     * Creates new form FirstEjecutation
     */
    public FirstEjecutation() {
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Iniciar programa");

        resizeImages();
        String text = "<html><body><p style='color: #BBBBBB;'>El nombre de la compañia y logotipo podrán ser <br/> cambiados por un usuario con permisos</p></body></html>";
        this.labeltext.setText(text);
    }

    /**
     * Redimenciona las imagenes de los botones para que se ajusten a el tamaño
     * necesario
     */
    private void resizeImages() {
        Icon resizedIcon = resizeIcon(buttonCancel.getIcon(), 30, 30);
        buttonCancel.setIcon(resizedIcon);

        resizedIcon = resizeIcon(buttonSave.getIcon(), 25, 22);
        buttonSave.setIcon(resizedIcon);
    }

    /**
     * Resize image for
     *
     * @param icon image for resize
     * @param width Width for image
     * @param height height for image
     * @return
     */
    private Icon resizeIcon(Icon icon, int width, int height) {
        if (icon instanceof ImageIcon imageIcon) {
            Image image = imageIcon.getImage();

            // Redimensionar la imagen al tamaño deseado
            Image resizedImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);

            // Crear un nuevo ImageIcon con la imagen redimensionada
            return new ImageIcon(resizedImage);
        }

        return icon; // Devolver el icono original si no es un ImageIcon
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        labelIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonImport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labeltext = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        fileChooser.setApproveButtonText("Abrir");
        fileChooser.setApproveButtonToolTipText("Selecciona esta imagen");
        fileChooser.setDialogTitle("Seleccionar imagen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 57, 103));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCafe.png"))); // NOI18N
        jPanel1.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 240, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circulo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 240, 250));

        buttonImport.setBackground(new java.awt.Color(46, 125, 18));
        buttonImport.setFont(new java.awt.Font("Jaldi", 1, 15)); // NOI18N
        buttonImport.setForeground(new java.awt.Color(255, 255, 255));
        buttonImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-search_116996.png"))); // NOI18N
        buttonImport.setText("Importar");
        buttonImport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 251, 203)));
        buttonImport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportActionPerformed(evt);
            }
        });
        jPanel1.add(buttonImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Jaldi", 0, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, 40));

        jLabel1.setFont(new java.awt.Font("Jaldi", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 43, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese un Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 340, 28));

        buttonCancel.setFont(new java.awt.Font("Jaldi", 1, 15)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(25, 130, 206));
        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconCircleMinBlue.png"))); // NOI18N
        buttonCancel.setText("Descartar");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 130, 206)));
        buttonCancel.setIconTextGap(5);
        buttonCancel.setPreferredSize(new java.awt.Dimension(109, 33));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 320, 140, -1));

        buttonSave.setBackground(new java.awt.Color(25, 130, 206));
        buttonSave.setFont(new java.awt.Font("Jaldi", 1, 15)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        buttonSave.setText("Guardar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 140, 33));

        labeltext.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labeltext.setIconTextGap(10);
        labeltext.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jPanel4.setBackground(new java.awt.Color(17, 57, 103));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeltext, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltext, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 439, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        String name = txtName.getText().trim();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre de la empresa");
            return;
        }

        if (logo.equals("")) {
            int response = JOptionPane.showConfirmDialog(null, "¿Desea continuar sin un logotipo?");
            if (JOptionPane.OK_OPTION != response) {
                return;
            }
        }

        Company company = new Company(0, name);
        company.setLogo("/" + (logo.equals("") ? "default" : logo));
        company.setDescripcion(description);
        
        System.out.println(company.toString());
        
        new JpaController().create(company);
        
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportActionPerformed
        fileChooser.showOpenDialog(jPanel1);
        try {
            String path = fileChooser.getSelectedFile().getPath();
            System.out.println(path);

            if (!path.equals("")) {
                String[] partes = path.split("/");
                logo = partes[partes.length - 1];
                
                String destino = Tools.ROOTPATH + "company/" + logo;

                Tools.copyFile(path, destino);
                
            }
        } catch (Exception e) {
            System.out.println("Cancelado");
        }
    }//GEN-LAST:event_buttonImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstEjecutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstEjecutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstEjecutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstEjecutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstEjecutation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonSave;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labeltext;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
