package com.unsis.view.panel;

import com.unsis.controller.JpaController;
import com.unsis.models.entity.Company;
import com.unsis.view.Main;
import java.util.ArrayList;

/**
 *
 * @author labtecweb10
 */
public class NavBar extends javax.swing.JPanel {

    private final JpaController controller;
    /**
     * Creates new form NavBar
     * @param main main window, used for child
     */
    public NavBar(Main main) {
        initComponents();
        this.setSize(207, 1024);
        PanelContainer options = new PanelContainer(main);
        options.setBounds(5, 150, 217, 149);
        this.add(options);
        this.controller = new JpaController();
        ArrayList<Company> company = controller.findAllEntities(Company.class);
        for (Company company1 : company) {
            jLabelNameEmpresa.setText(company1.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameEmpresa = new javax.swing.JLabel();
        buttonHome = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 57, 103));

        jLabelNameEmpresa.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabelNameEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNameEmpresa.setText("Empresa");

        buttonHome.setBackground(new java.awt.Color(17, 57, 103));
        buttonHome.setForeground(new java.awt.Color(255, 255, 255));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeIcon.png"))); // NOI18N
        buttonHome.setText("Inicio");
        buttonHome.setToolTipText("");
        buttonHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonHome.setContentAreaFilled(false);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelNameEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(887, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonHome;
    private javax.swing.JLabel jLabelNameEmpresa;
    // End of variables declaration//GEN-END:variables
}
