/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe;

/**
 *
 * @author america
 */
public class PanelAjustes extends javax.swing.JPanel {

    /**
     * Creates new form PanelAjustes
     */
    public PanelAjustes() {
        initComponents();
        jButton1.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeldate = new javax.swing.JLabel();
        labelfilter = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        labelfilter1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelfilter2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        labelfilter3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        labelfilter4 = new javax.swing.JLabel();
        labelfilter5 = new javax.swing.JLabel();
        labelfilter6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Labeajustes = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeldate.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        labeldate.setForeground(new java.awt.Color(118, 125, 142));
        labeldate.setText("Habilitado solo para administrador ");
        jPanel1.add(labeldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        labelfilter.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter.setText("Editar logotipo");
        jPanel1.add(labelfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, 39));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 370, 50));

        labelfilter1.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter1.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter1.setText("Facebook");
        jPanel1.add(labelfilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 140, 39));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cafe/72457166-marco-circular-monocromo-con-ilustración-de-vector-de-taza-de-café.jpg"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 370, 370));

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 700, 260, 50));

        labelfilter2.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter2.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter2.setText("Editar Nombre de la empresa");
        jPanel1.add(labelfilter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 350, 39));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 440, 40));

        labelfilter3.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter3.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter3.setText("Editar porciento de IVA");
        jPanel1.add(labelfilter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 290, 39));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 450, 50));

        labelfilter4.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter4.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter4.setText("Cantidad en decimales");
        jPanel1.add(labelfilter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 290, 39));

        labelfilter5.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter5.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter5.setText("Contactos de empresa");
        jPanel1.add(labelfilter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 290, 39));

        labelfilter6.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter6.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter6.setText("Instagram");
        jPanel1.add(labelfilter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 140, 39));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, 270, 40));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 550, 280, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Importar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, 260, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1620, 860));

        Labeajustes.setFont(new java.awt.Font("Jaldi", 0, 48)); // NOI18N
        Labeajustes.setForeground(new java.awt.Color(82, 146, 222));
        Labeajustes.setText("Ajustes");
        add(Labeajustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labeajustes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labelfilter;
    private javax.swing.JLabel labelfilter1;
    private javax.swing.JLabel labelfilter2;
    private javax.swing.JLabel labelfilter3;
    private javax.swing.JLabel labelfilter4;
    private javax.swing.JLabel labelfilter5;
    private javax.swing.JLabel labelfilter6;
    // End of variables declaration//GEN-END:variables
}
