package com.unsis.view.panel;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;

public class PanelContainer extends javax.swing.JPanel {

    public PanelContainer() {
        initComponents();
        rendererAllComoboBox();

        comboHomeware.setModel(getModel(new String[] {"Mercancia disponible", "Ventas", "Menu"})); // Establece el modelo en el JComboBox
        comboHomeware.setBackground(Color.BLUE);
    }

    /**
     * Crea un modelo
     *
     * @return
     */
    private DefaultComboBoxModel getModel(String[] texts) {
        DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel<JLabel>(generateOptions(texts));

        return model;
    }

    /**
     * Genera un array de JLabels para retornarlos como lista de opciones
     * @param texts Textos que incluye cada JLabel
     * @return Array de JLabels
     */
    private JLabel[] generateOptions(String[] texts) {
        ArrayList<JLabel> labels = new ArrayList<>();
        labels.add(labelHomewore);
        JLabel label;
        for (String text : texts) {
            label = new JLabel(text);
            label.setBackground(new java.awt.Color(17, 57, 103));
            label.setForeground(new java.awt.Color(255, 255, 255));
            
            labels.add(label);
        }
        
        return (JLabel[]) labels.toArray(new JLabel[labels.size()]);
    }

    /**
     * Rescribe el metodo de renderizado de los ComboBox para mostrar JLabel's
     */
    private void rendererAllComoboBox() {
        DefaultListCellRenderer listCellRenderer = new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof JLabel) {
                    return (JLabel) value;
                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            }
        };
        comboHomeware.setRenderer(listCellRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelHomewore = new javax.swing.JLabel();
        comboHomeware = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();

        labelHomewore.setBackground(new java.awt.Color(17, 57, 103));
        labelHomewore.setForeground(new java.awt.Color(255, 255, 255));
        labelHomewore.setIcon(new javax.swing.ImageIcon("C:\\Users\\jared\\OneDrive\\Documentos\\NetBeansProjects\\Unsis\\SalePoint\\src\\main\\java\\com\\unsis\\images\\homeworeIcon.png")); // NOI18N
        labelHomewore.setText("Almacén");

        setBackground(new java.awt.Color(60, 75, 112));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        comboHomeware.setBackground(new java.awt.Color(60, 75, 112));
        comboHomeware.setForeground(new java.awt.Color(255, 255, 255));
        comboHomeware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "iren" }));
        comboHomeware.setBorder(BorderFactory.createLineBorder(new Color(27, 53, 103), 2));
        comboHomeware.setFocusCycleRoot(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        add(comboHomeware, gridBagConstraints);

        jComboBox3.setBackground(new java.awt.Color(0, 0, 102));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        add(jComboBox3, gridBagConstraints);

        jComboBox4.setBackground(new java.awt.Color(60, 75, 112));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        add(jComboBox4, gridBagConstraints);

        jComboBox5.setBackground(new java.awt.Color(60, 75, 112));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        add(jComboBox5, gridBagConstraints);

        jComboBox6.setBackground(new java.awt.Color(60, 75, 112));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        add(jComboBox6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboHomeware;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel labelHomewore;
    // End of variables declaration//GEN-END:variables
}
