/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unsis.view.panel;

import com.toedter.calendar.JCalendar;
import com.unsis.clases.Tools;
import java.awt.Image;
import java.net.URL;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author labtecweb09
 */
public class RegisterEmployed extends javax.swing.JPanel {

    JCalendar dateIngres;

    /**
     * Creates new form AltaEmpleado
     */
    public RegisterEmployed() {
        initComponents();
        panelInternal.setSize(1696, 894);
        this.setSize(1696, 894);
        this.setBounds(0, 0, this.getWidth(), this.getHeight());

        dateIngres = new JCalendar(new Date());
        dateIngres.setVisible(false);
        panelInternal.add(dateIngres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 230, 250));
        panelInternal.setComponentZOrder(dateIngres, 0);
        resizeImages();
    }

    /**
     * Redimenciona las imagenes de los botones para que se ajusten a el tamaño
     * necesario
     */
    private void resizeImages() {
        Tools tools = new Tools();
        Icon resizedIcon = tools.resizeIcon(buttonSave.getIcon(), 30, 30);
        buttonSave.setIcon(resizedIcon);

        resizedIcon = tools.resizeIcon(buttonDiscard.getIcon(), 35, 35);
        buttonDiscard.setIcon(resizedIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        panelInternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        buttonDiscard = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonCalendar = new javax.swing.JToggleButton();
        jTextField9 = new javax.swing.JTextField();
        check = new javax.swing.JCheckBox();
        checkSalePoint = new javax.swing.JCheckBox();
        checkOrders = new javax.swing.JCheckBox();
        checkSettingsApp = new javax.swing.JCheckBox();
        checkSettingsCompany = new javax.swing.JCheckBox();
        checkCourt = new javax.swing.JCheckBox();
        checkRegisterExpenses = new javax.swing.JCheckBox();
        checkExpensesHistory = new javax.swing.JCheckBox();
        checkListEmployes = new javax.swing.JCheckBox();
        updateEmployes = new javax.swing.JCheckBox();
        checkRegisterEmploy = new javax.swing.JCheckBox();
        checkRegisterProducts = new javax.swing.JCheckBox();
        checkInventory = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buttonSelectImage = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        fileChooser.setDialogTitle("Seleccionar imagen");
        fileChooser.setFileHidingEnabled(false);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Jaldi", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 41, 87));
        jLabel1.setText("Alta de empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, 40));

        panelInternal.setBackground(new java.awt.Color(255, 255, 255));
        panelInternal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 146, 222));
        jLabel2.setText("Informacion empresarial");
        panelInternal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, -1));
        panelInternal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 150, 30));

        jLabel4.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 125, 142));
        jLabel4.setText("Puesto");
        panelInternal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 125, 142));
        jLabel5.setText("Apellido materno");
        panelInternal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));
        panelInternal.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 170, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 125, 142));
        jLabel6.setText("N.Empleado");
        panelInternal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        panelInternal.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 30));

        jLabel7.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 125, 142));
        jLabel7.setText("Correo");
        panelInternal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        panelInternal.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 30));

        jLabel8.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(118, 125, 142));
        jLabel8.setText("Telefono");
        panelInternal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(118, 125, 142));
        jLabel10.setText("Fecha Nacimiento");
        panelInternal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        panelInternal.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 30));

        jLabel11.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(118, 125, 142));
        jLabel11.setText("Apellido paterno");
        panelInternal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
        panelInternal.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInternal.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 140, 30));

        jLabel12.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(118, 125, 142));
        jLabel12.setText("Fecha Ingreso");
        panelInternal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(118, 125, 142));
        jLabel13.setText("Estado");
        panelInternal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInternal.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 140, 30));

        jLabel15.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(118, 125, 142));
        jLabel15.setText("Ubicacion");
        panelInternal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInternal.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 140, 30));

        jLabel16.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(118, 125, 142));
        jLabel16.setText("Area");
        panelInternal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInternal.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 140, 30));

        jLabel22.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(82, 146, 222));
        jLabel22.setText("Informacion personal");
        panelInternal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, -1));

        jLabel23.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(118, 125, 142));
        jLabel23.setText("Nombre");
        panelInternal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 40));

        buttonDiscard.setBackground(new java.awt.Color(153, 11, 11));
        buttonDiscard.setFont(new java.awt.Font("Jaldi", 0, 20)); // NOI18N
        buttonDiscard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDiscard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconCircleMin.png"))); // NOI18N
        buttonDiscard.setText("Descartar");
        panelInternal.add(buttonDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 650, 210, 50));

        buttonSave.setBackground(new java.awt.Color(46, 125, 18));
        buttonSave.setFont(new java.awt.Font("Jaldi", 0, 20)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        buttonSave.setText("Guardar");
        panelInternal.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 650, 220, 50));

        buttonCalendar.setText("-- : -- : ----");
        buttonCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalendarActionPerformed(evt);
            }
        });
        panelInternal.add(buttonCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 30));
        panelInternal.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 170, 30));

        check.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        check.setForeground(new java.awt.Color(118, 125, 142));
        check.setText("Lista de productos");
        check.setOpaque(false);
        panelInternal.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, -1, -1));

        checkSalePoint.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkSalePoint.setForeground(new java.awt.Color(118, 125, 142));
        checkSalePoint.setText("Punto de venta");
        checkSalePoint.setOpaque(false);
        panelInternal.add(checkSalePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 140, -1, -1));

        checkOrders.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkOrders.setForeground(new java.awt.Color(118, 125, 142));
        checkOrders.setText("Pedidos entranates");
        checkOrders.setOpaque(false);
        panelInternal.add(checkOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 180, -1, -1));

        checkSettingsApp.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkSettingsApp.setForeground(new java.awt.Color(118, 125, 142));
        checkSettingsApp.setText("Ajustes del aplicativo");
        checkSettingsApp.setOpaque(false);
        panelInternal.add(checkSettingsApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 280, -1, -1));

        checkSettingsCompany.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkSettingsCompany.setForeground(new java.awt.Color(118, 125, 142));
        checkSettingsCompany.setText("Ajustes emplresariales");
        checkSettingsCompany.setOpaque(false);
        panelInternal.add(checkSettingsCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 320, -1, -1));

        checkCourt.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkCourt.setForeground(new java.awt.Color(118, 125, 142));
        checkCourt.setText("Corte de caja");
        checkCourt.setOpaque(false);
        panelInternal.add(checkCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 420, -1, -1));

        checkRegisterExpenses.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkRegisterExpenses.setForeground(new java.awt.Color(118, 125, 142));
        checkRegisterExpenses.setText("Registrar gastos");
        checkRegisterExpenses.setOpaque(false);
        panelInternal.add(checkRegisterExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 460, -1, -1));

        checkExpensesHistory.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkExpensesHistory.setForeground(new java.awt.Color(118, 125, 142));
        checkExpensesHistory.setText("Historial de gastos");
        checkExpensesHistory.setOpaque(false);
        panelInternal.add(checkExpensesHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 500, -1, -1));

        checkListEmployes.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkListEmployes.setForeground(new java.awt.Color(118, 125, 142));
        checkListEmployes.setText("Lista de Empleados");
        checkListEmployes.setOpaque(false);
        panelInternal.add(checkListEmployes, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, -1, -1));

        updateEmployes.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        updateEmployes.setForeground(new java.awt.Color(118, 125, 142));
        updateEmployes.setText("Modificación de empleados");
        updateEmployes.setOpaque(false);
        panelInternal.add(updateEmployes, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, -1, -1));

        checkRegisterEmploy.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkRegisterEmploy.setForeground(new java.awt.Color(118, 125, 142));
        checkRegisterEmploy.setText("Registro de empleados");
        checkRegisterEmploy.setOpaque(false);
        panelInternal.add(checkRegisterEmploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, -1, -1));

        checkRegisterProducts.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkRegisterProducts.setForeground(new java.awt.Color(118, 125, 142));
        checkRegisterProducts.setText("Modificación de productos");
        checkRegisterProducts.setOpaque(false);
        panelInternal.add(checkRegisterProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, -1, -1));

        checkInventory.setFont(new java.awt.Font("Jaldi", 0, 16)); // NOI18N
        checkInventory.setForeground(new java.awt.Color(118, 125, 142));
        checkInventory.setText("Alta de productos");
        checkInventory.setOpaque(false);
        panelInternal.add(checkInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, -1, -1));

        jLabel27.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(118, 125, 142));
        jLabel27.setText("Contabilidad");
        panelInternal.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 380, 110, 40));

        jLabel24.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(118, 125, 142));
        jLabel24.setText("Recursos Humanos");
        panelInternal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 210, 40));

        jLabel3.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 125, 142));
        jLabel3.setText("Ajustes");
        panelInternal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 240, 110, 40));

        jLabel25.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(118, 125, 142));
        jLabel25.setText("Ventas");
        panelInternal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 90, 90, 40));

        jLabel26.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(118, 125, 142));
        jLabel26.setText("Almacen");
        panelInternal.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 120, 40));

        jLabel9.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(82, 146, 222));
        jLabel9.setText("Accesos");
        panelInternal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 213, -1));

        jLabel17.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(82, 146, 222));
        jLabel17.setText("Foto de Empleado");
        panelInternal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 240, -1));

        buttonSelectImage.setBackground(new java.awt.Color(0, 102, 102));
        buttonSelectImage.setForeground(new java.awt.Color(255, 255, 255));
        buttonSelectImage.setText("Elegir Imagen");
        buttonSelectImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSelectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectImageActionPerformed(evt);
            }
        });
        panelInternal.add(buttonSelectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 150, 140));

        jLabel14.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(82, 146, 222));
        jLabel14.setText("Información de cuenta");
        panelInternal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 310, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(118, 125, 142));
        jLabel18.setText("Usuario");
        panelInternal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));
        panelInternal.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 210, 30));

        jLabel19.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(118, 125, 142));
        jLabel19.setText("Contraseña temporal");
        panelInternal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 240, -1));
        panelInternal.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 210, 30));

        add(panelInternal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 1610, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalendarActionPerformed
        if (dateIngres.isVisible()) {
            dateIngres.setVisible(false);
            buttonCalendar.setText(dateIngres.getDate().toLocaleString());
            System.err.println("Fecha seleccionada: " + dateIngres.getDate().toLocaleString());
        } else {
            dateIngres.setVisible(true);
            buttonCalendar.setText("-- : -- : ----");
        }
    }//GEN-LAST:event_buttonCalendarActionPerformed

    private void buttonSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectImageActionPerformed
        fileChooser.showDialog(this, "Aceptar");

        String path = fileChooser.getSelectedFile().getPath();

        if (!path.isEmpty()) {
            Tools tools = new Tools();
            this.buttonSelectImage.setIcon(tools.resizeIcon(
                    new ImageIcon(path), 140, 140));

            this.buttonSelectImage.setOpaque(false);
            this.buttonSelectImage.setText("");

        }
    }//GEN-LAST:event_buttonSelectImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonCalendar;
    private javax.swing.JButton buttonDiscard;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSelectImage;
    private javax.swing.JCheckBox check;
    private javax.swing.JCheckBox checkCourt;
    private javax.swing.JCheckBox checkExpensesHistory;
    private javax.swing.JCheckBox checkInventory;
    private javax.swing.JCheckBox checkListEmployes;
    private javax.swing.JCheckBox checkOrders;
    private javax.swing.JCheckBox checkRegisterEmploy;
    private javax.swing.JCheckBox checkRegisterExpenses;
    private javax.swing.JCheckBox checkRegisterProducts;
    private javax.swing.JCheckBox checkSalePoint;
    private javax.swing.JCheckBox checkSettingsApp;
    private javax.swing.JCheckBox checkSettingsCompany;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelInternal;
    private javax.swing.JCheckBox updateEmployes;
    // End of variables declaration//GEN-END:variables
}
