/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unsis.view.panel;

/**
 *
 * @author america
 */
public class RegisterExpenses extends javax.swing.JPanel {

    /**
     * Creates new form PanelGasto
     */
    public RegisterExpenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1gastos = new javax.swing.JPanel();
        Labebillsl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGastos = new javax.swing.JTable();
        labelfilter = new javax.swing.JLabel();
        labeldescription = new javax.swing.JLabel();
        labelcost = new javax.swing.JLabel();
        labelvoucher = new javax.swing.JLabel();
        labelamount = new javax.swing.JLabel();
        labelcategory = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelGeneral = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        labelmonth = new javax.swing.JLabel();
        labelproduct = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtproductp = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtproduct = new javax.swing.JTextField();
        combobxproductp = new javax.swing.JComboBox<>();
        comboboxcategory = new javax.swing.JComboBox<>();
        comboboxmonth = new javax.swing.JComboBox<>();
        comboboxproduct = new javax.swing.JComboBox<>();
        buttonvoucher = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1gastos.setBackground(new java.awt.Color(255, 255, 255));
        Panel1gastos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Labebillsl.setFont(new java.awt.Font("Jaldi", 0, 48)); // NOI18N
        Labebillsl.setForeground(new java.awt.Color(82, 146, 222));
        Labebillsl.setText("Gastos");
        Panel1gastos.add(Labebillsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        tableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripcion", "Autorizado Por", "Realizado", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tableGastos);

        Panel1gastos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 540, 660));

        labelfilter.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelfilter.setForeground(new java.awt.Color(82, 146, 222));
        labelfilter.setText("Filtro de busqueda");
        Panel1gastos.add(labelfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 233, 39));

        labeldescription.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labeldescription.setForeground(new java.awt.Color(118, 125, 142));
        labeldescription.setText("Descripcion");
        Panel1gastos.add(labeldescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        labelcost.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelcost.setForeground(new java.awt.Color(118, 125, 142));
        labelcost.setText("Costo de compra");
        Panel1gastos.add(labelcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, -1, -1));

        labelvoucher.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelvoucher.setForeground(new java.awt.Color(118, 125, 142));
        labelvoucher.setText("Adjunte de comprobante");
        Panel1gastos.add(labelvoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 460, -1, -1));

        labelamount.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelamount.setForeground(new java.awt.Color(118, 125, 142));
        labelamount.setText("Monto");
        Panel1gastos.add(labelamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        labelcategory.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelcategory.setForeground(new java.awt.Color(118, 125, 142));
        labelcategory.setText("Categoria");
        Panel1gastos.add(labelcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 146, 222));
        jLabel3.setText("Informacion especifica");
        Panel1gastos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, 270, 39));

        LabelGeneral.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        LabelGeneral.setForeground(new java.awt.Color(82, 146, 222));
        LabelGeneral.setText("Informacion general ");
        Panel1gastos.add(LabelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 270, 39));

        labeldate.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labeldate.setForeground(new java.awt.Color(118, 125, 142));
        labeldate.setText("Fecha");
        Panel1gastos.add(labeldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        labelmonth.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelmonth.setForeground(new java.awt.Color(118, 125, 142));
        labelmonth.setText("Mes de compra");
        Panel1gastos.add(labelmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        labelproduct.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        labelproduct.setForeground(new java.awt.Color(118, 125, 142));
        labelproduct.setText("Tipo de producto");
        Panel1gastos.add(labelproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Jaldi", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(118, 125, 142));
        jLabel13.setText("Tipo de producto");
        Panel1gastos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));
        Panel1gastos.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 180, 40));
        Panel1gastos.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 180, 40));
        Panel1gastos.add(txtproductp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 120, 40));
        Panel1gastos.add(txtdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 180, 40));
        Panel1gastos.add(txtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 180, 40));

        combobxproductp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel1gastos.add(combobxproductp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 120, 40));

        comboboxcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel1gastos.add(comboboxcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 190, 40));

        comboboxmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel1gastos.add(comboboxmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 190, 40));

        comboboxproduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel1gastos.add(comboboxproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 190, 40));

        buttonvoucher.setBackground(new java.awt.Color(204, 255, 255));
        buttonvoucher.setFont(new java.awt.Font("Jaldi", 0, 10)); // NOI18N
        buttonvoucher.setText("Arrastre y suelte el archivo aqui para subirlo");
        buttonvoucher.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Panel1gastos.add(buttonvoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 250, 170));

        add(Panel1gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 810));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labebillsl;
    private javax.swing.JLabel LabelGeneral;
    private javax.swing.JPanel Panel1gastos;
    private javax.swing.JButton buttonvoucher;
    private javax.swing.JComboBox<String> comboboxcategory;
    private javax.swing.JComboBox<String> comboboxmonth;
    private javax.swing.JComboBox<String> comboboxproduct;
    private javax.swing.JComboBox<String> combobxproductp;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelamount;
    private javax.swing.JLabel labelcategory;
    private javax.swing.JLabel labelcost;
    private javax.swing.JLabel labeldate;
    private javax.swing.JLabel labeldescription;
    private javax.swing.JLabel labelfilter;
    private javax.swing.JLabel labelmonth;
    private javax.swing.JLabel labelproduct;
    private javax.swing.JLabel labelvoucher;
    private javax.swing.JTable tableGastos;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtproductp;
    // End of variables declaration//GEN-END:variables
}
