package com.unsis.view.panel;

import com.unsis.clases.Tools;
import com.unsis.view.Main;
import javax.swing.Icon;

/**
 *
 * @author jared
 */
public class ToolBar extends javax.swing.JPanel {

    private Main mainWindow;
    /**
     * Creates new form ToolBar
     * @param mainWindow
     */
    public ToolBar(Main mainWindow) {
        initComponents();
        this.setSize(1700, 60);
        this.setBounds(217, 0, 1700, 70);
        this.resizeImages();
        
        this.mainWindow = mainWindow;
    }
    
     /**
     * Redimenciona las imagenes de los botones para que se ajusten a el tamaño
     * necesario
     */
    private void resizeImages() {
        Tools tools = new Tools();
        Icon resizedIcon = tools.resizeIcon(buttonCloseSesion.getIcon(), 50, 50);
        buttonCloseSesion.setIcon(resizedIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonCloseSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jared Galicia");

        buttonCloseSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeSession.jpg"))); // NOI18N
        buttonCloseSesion.setToolTipText("Cerrar Sesión");
        buttonCloseSesion.setBorder(null);
        buttonCloseSesion.setContentAreaFilled(false);
        buttonCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 794, Short.MAX_VALUE)
                .addComponent(buttonCloseSesion)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonCloseSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(labelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseSesionMouseClicked
        mainWindow.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonCloseSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCloseSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelProfile;
    // End of variables declaration//GEN-END:variables
}
