package com.unsis.view.panel;

import com.unsis.clases.Session;
import com.unsis.clases.Tools;
import com.unsis.models.constants.Constants;
import com.unsis.view.Main;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author jared
 */
public class ToolBar extends javax.swing.JPanel {

    private final Main mainWindow;
    /**
     * Creates new form ToolBar
     * @param mainWindow
     */
    public ToolBar(Main mainWindow) {
        initComponents();
        this.setSize(1700, 60);
        this.setBounds(217, 0, 1700, 70);
        this.resizeImages();
        
        this.mainWindow = mainWindow;

        this.labelName.setText(Session.getAccount().getIdempleado().getNombre());
        
        String rutaImagen = Constants.PATH_PROFILE + Session.getAccount().getFotoperfil();
        System.out.println(rutaImagen);
        ImageIcon icono = new ImageIcon(rutaImagen);
        System.out.println(icono);
        labelProfile.setIcon(icono);
    }
    
     /**
     * Redimenciona las imagenes de los botones para que se ajusten a el tamaño
     * necesario
     */
    private void resizeImages() {
        Tools tools = new Tools();
        Icon resizedIcon = tools.resizeIcon(buttonCloseSesion.getIcon(), 50, 50);
        buttonCloseSesion.setIcon(resizedIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfile = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        buttonCloseSesion = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user1.png"))); // NOI18N

        labelName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelName.setText("Jared Galicia");

        buttonCloseSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeSession.jpg"))); // NOI18N
        buttonCloseSesion.setToolTipText("Cerrar Sesión");
        buttonCloseSesion.setBorder(null);
        buttonCloseSesion.setContentAreaFilled(false);
        buttonCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseSesionMouseClicked(evt);
            }
        });

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backArrow.png"))); // NOI18N
        buttonBack.setBorder(null);
        buttonBack.setContentAreaFilled(false);
        buttonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCloseSesion)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCloseSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseSesionMouseClicked
        mainWindow.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonCloseSesionMouseClicked

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        mainWindow.showPreviusPanel();
        mainWindow.requestFocus();
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCloseSesion;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelProfile;
    // End of variables declaration//GEN-END:variables
}
