package com.unsis.view.panel;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import com.unsis.clases.PanelDesp;

/**
 *
 * @author labtecweb07
 */
public class ventasDesp extends javax.swing.JPanel {
    /**
     * Creates new form ventasDesp
     */
    public ventasDesp() {
        initComponents();
        this.setBounds(0, 0, 899, 691);
        /*
        Aqui creo los objetos para la cabecera y el hijo para desplegar, esto
        para poder agregarle imagenes y modificar los componentes.
        */
        HeadWrapperPanel hPanel1 = new HeadWrapperPanel();
        HeadWrapperPanel hPanel2 = new HeadWrapperPanel();
        ChildWrapperPanel chPanel1 = new ChildWrapperPanel();

//        hPanel1.getImgLabel().setIcon(new ImageIcon(getClass().getResource("/user0.png")));
        hPanel2.getImgLabel().setIcon(new ImageIcon(getClass().getResource("/user1.png")));
        
        /*
        Aqui lo agrego a una matriz que contendra el header y el child.
        */
        JPanel[][] p = new JPanel[][]{
            {hPanel1, chPanel1},
            {hPanel2, new ChildWrapperPanel()}

        };
        
        /*
        Creo el objeto de los paneles desplegables.
        */
        PanelDesp desp = new PanelDesp(p);
        
        deplegablesPanel.add(desp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        deplegablesPanel = new javax.swing.JPanel();

        jLabel2.setBackground(new java.awt.Color(3, 43, 89));
        jLabel2.setFont(new java.awt.Font("Jaldi", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 56, 112));
        jLabel2.setText("Registro de ventas realizadas");

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        deplegablesPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 520, Short.MAX_VALUE))
                    .addComponent(deplegablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deplegablesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deplegablesPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
