package com.unsis.view;

import com.unsis.clases.Clock;
import com.unsis.clases.Tools;
import com.unsis.controller.JpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author labtecweb10
 */
public class ResetPassword extends javax.swing.JFrame {

    private Clock timer;
    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Recupera tu acceso");

        validateCode.setSize(448, 241);
        validateCode.setLocationRelativeTo(this);
        
        changePassword.setSize(448, 241);
        changePassword.setLocationRelativeTo(this);
        
        labelWarnig.setVisible(false);
        this.textMessage.setText("""
                                       Recibir\u00e1s un mensaje con código
                                       recuperación. No lo compartas con nadie
                                 
                                 
                                            Por favor, escribe tu correo electr\u00f3nico.
                                            nueva por correo electr\u00f3nico.""");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validateCode = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        buttonContinue = new javax.swing.JButton();
        labelTimer = new javax.swing.JLabel();
        labelWarnig = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        changePassword = new javax.swing.JDialog();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMessage = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMailReset = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();

        validateCode.setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
        });
        jPanel2.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, 25));

        buttonContinue.setText("Continuar");
        buttonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinueActionPerformed(evt);
            }
        });
        jPanel2.add(buttonContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 30));

        labelTimer.setText("El código será valido durante 60 Seg");
        jPanel2.add(labelTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 100, 270, -1));

        labelWarnig.setBackground(new java.awt.Color(204, 153, 0));
        labelWarnig.setForeground(new java.awt.Color(204, 153, 0));
        labelWarnig.setText("Por favor ingrese el codigo");
        jPanel2.add(labelWarnig, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese el código recibido en su correo electronico");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 50));

        javax.swing.GroupLayout validateCodeLayout = new javax.swing.GroupLayout(validateCode.getContentPane());
        validateCode.getContentPane().setLayout(validateCodeLayout);
        validateCodeLayout.setHorizontalGroup(
            validateCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        validateCodeLayout.setVerticalGroup(
            validateCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        changePassword.setModal(true);
        changePassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changePassword.getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 25));

        txtPasswordConfirm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPasswordConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasswordConfirm.setText("jPasswordField1");
        txtPasswordConfirm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changePassword.getContentPane().add(txtPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, 25));

        jButton1.setText("Actualizar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        changePassword.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, 25));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Ingresa tu nueva contraseña");
        changePassword.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 248, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(17, 57, 103));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textMessage.setEditable(false);
        textMessage.setColumns(20);
        textMessage.setForeground(new java.awt.Color(180, 184, 186));
        textMessage.setRows(5);
        textMessage.setBorder(null);
        textMessage.setOpaque(false);
        jScrollPane1.setViewportView(textMessage);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, 370, -1));

        jLabel5.setFont(new java.awt.Font("Jaldi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 125, 142));
        jLabel5.setText("Correo Electronico");

        txtMailReset.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonSend.setBackground(new java.awt.Color(0, 102, 102));
        buttonSend.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonSend.setForeground(new java.awt.Color(255, 255, 255));
        buttonSend.setText("Enviar");
        buttonSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtMailReset, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMailReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 370, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSendMouseClicked
        String mail = txtMailReset.getText().trim();
        String code = Tools.generateCode();
        int response = new JpaController().sendMessage(mail, code);
        
        System.out.println(response);
        
        String message;
        
        switch (response) {
            case 200 -> {
                message = "";
                timer = new Clock(labelTimer);
                timer.start();
                validateCode.show();
            }
            case 300 ->
                message = "";
            case 304 ->
                message = "Credenciales de correo no disponibles";
            case 400 ->
                message = "El correo no corresponde a ningun usuario";
            default ->
                message = "Código no esperado";
        }

        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_buttonSendMouseClicked

    private void buttonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinueActionPerformed
        String codeInp = txtCode.getText().trim();
        
        if (codeInp.equals("")) {
            labelWarnig.setVisible(true);
            return;
        }
        
        if (Tools.matchCode(codeInp)) {
            JOptionPane.showMessageDialog(null, "código valido");
            validateCode.setVisible(false);
            changePassword.show();
        } else {
            JOptionPane.showMessageDialog(null, "El código ingresado es invalido");
        }
        
    }//GEN-LAST:event_buttonContinueActionPerformed

    /**
     * Agrega un espacio en la posicion 5 del componente txtCode para cumplir con el formato
     * del código de recuperación
     * @param evt Obj con propiedades del eento KeyPressed
     */
    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        if (txtCode.getText().trim().length() == 4) {
            txtCode.setText(txtCode.getText() + " ");
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pass = txtPassword.getText().trim();
        String passConfirm = txtPasswordConfirm.getText().trim();
        
        if (pass.equals(passConfirm)) {
//            Actualiza contraseña
            this.dispose();
           
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContinue;
    private javax.swing.JButton buttonSend;
    private javax.swing.JDialog changePassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JLabel labelWarnig;
    private javax.swing.JTextArea textMessage;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMailReset;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JDialog validateCode;
    // End of variables declaration//GEN-END:variables
}
